// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - run flutterfire configure.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'web-api-key',
    appId: '1:1234567890:web:abcdef',
    messagingSenderId: '1234567890',
    projectId: 'flutterfire-starter',
    authDomain: 'flutterfire-starter.firebaseapp.com',
    storageBucket: 'flutterfire-starter.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'android-api-key',
    appId: '1:1234567890:android:abcdef',
    messagingSenderId: '1234567890',
    projectId: 'flutterfire-starter',
    storageBucket: 'flutterfire-starter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ios-api-key',
    appId: '1:1234567890:ios:abcdef',
    messagingSenderId: '1234567890',
    projectId: 'flutterfire-starter',
    storageBucket: 'flutterfire-starter.appspot.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'macos-api-key',
    appId: '1:1234567890:ios:abcdef',
    messagingSenderId: '1234567890',
    projectId: 'flutterfire-starter',
    storageBucket: 'flutterfire-starter.appspot.com',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'windows-api-key',
    appId: '1:1234567890:web:abcdef',
    messagingSenderId: '1234567890',
    projectId: 'flutterfire-starter',
    authDomain: 'flutterfire-starter.firebaseapp.com',
    storageBucket: 'flutterfire-starter.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
